const {chromium}=require('playwright');
const fs=require('fs'),path=require('path'),os=require('os'),http=require('http'),assert=require('assert');
const fixture=`<meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font:20px system-ui}button,input,a{display:block;margin:20px;padding:10px}.tail{height:2500px}</style><button id="menu" onclick="document.querySelector('#result').textContent='Открыто'">Меню</button><p id="result">Закрыто</p><input id="field"><input id="password" type="password"><div id="box" style="height:100px;overflow:auto"><div style="height:900px">Вложенная прокрутка</div></div><a id="next" href="/next">Дальше</a><a id="blank" href="/new" target="_blank">Новое окно</a><form action="/post" method="POST"><button type="submit" id="submit">Заявка</button></form><div class="tail"></div>`;
(async()=>{let posts=0;const server=http.createServer((req,res)=>{if(req.method==='POST')posts++;res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});res.end(fixture);}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const site='http://127.0.0.1:'+server.address().port,root=fs.mkdtempSync(path.join(os.tmpdir(),'mobile-qa-desktop-')),ext=path.join(root,'extension');fs.cpSync(path.resolve(__dirname,'../extension'),ext,{recursive:true});const manifest=JSON.parse(fs.readFileSync(path.join(ext,'manifest.json')));manifest.host_permissions=['http://127.0.0.1/*'];fs.writeFileSync(path.join(ext,'manifest.json'),JSON.stringify(manifest));let context;
try{context=await chromium.launchPersistentContext(path.join(root,'profile'),{channel:'chromium',headless:true,viewport:{width:1500,height:1100},ignoreDefaultArgs:['--disable-extensions'],args:['--enable-unsafe-extension-debugging']});const cd=await context.browser().newBrowserCDPSession(),{id}=await cd.send('Extensions.loadUnpacked',{path:ext});const source=await context.newPage();await source.goto(site+'/');const panel=await context.newPage(),errors=[];panel.on('pageerror',e=>errors.push(e.message));await panel.goto(`chrome-extension://${id}/panel.html`);const worker=context.serviceWorkers()[0],sourceId=await worker.evaluate(async url=>(await chrome.tabs.query({url:url+'/*'}))[0].id,site);await panel.goto(`chrome-extension://${id}/panel.html?url=${encodeURIComponent(site+'/')}&source=${sourceId}`);
await panel.waitForFunction(()=>document.querySelectorAll('.device-status').length===4&&[...document.querySelectorAll('.device-status')].every(x=>x.textContent==='Подключён'));assert.equal(source.url(),site+'/');assert(await panel.locator('#follow-source').isChecked());
await source.bringToFront();await source.locator('#menu').click();await panel.waitForTimeout(300);let frames=panel.frames().filter(f=>f.url().startsWith(site));console.log('DESKTOP',await panel.locator('#source-status').textContent(),await panel.locator('#status').textContent(),await Promise.all(frames.map(f=>f.locator('#result').textContent())));assert((await Promise.all(frames.map(f=>f.locator('#result').textContent()))).every(x=>x==='Открыто'));
await source.locator('#field').fill('Две вкладки');await panel.waitForTimeout(200);assert((await Promise.all(frames.map(f=>f.locator('#field').inputValue()))).every(x=>x==='Две вкладки'));
await source.evaluate(()=>scrollTo(0,900));await Promise.all(frames.map(f=>f.waitForFunction(()=>scrollY>500)));assert((await Promise.all(frames.map(f=>f.evaluate(()=>scrollY>500)))).every(Boolean));

// Mobile and tablet actions must reach the ordinary desktop tab and every peer.
await panel.bringToFront();frames=panel.frames().filter(f=>f.url().startsWith(site));
await frames[0].locator('#field').fill('Из телефона');await source.waitForFunction(()=>document.querySelector('#field').value==='Из телефона');
assert((await Promise.all(frames.map(f=>f.locator('#field').inputValue()))).every(x=>x==='Из телефона'));
await frames[3].locator('#field').fill('Из планшета');await source.waitForFunction(()=>document.querySelector('#field').value==='Из планшета');
await frames[0].locator('#password').fill('local-only');await panel.waitForTimeout(250);assert.equal(await source.locator('#password').inputValue(),'');assert.equal(await frames[1].locator('#password').inputValue(),'');
await frames[0].locator('#box').evaluate(e=>e.scrollIntoView({block:'center'}));await panel.waitForTimeout(500);const outer=await (await frames[0].frameElement()).boundingBox();const inner=await frames[0].locator('#box').evaluate(e=>{const r=e.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2,w:innerWidth};});await panel.mouse.move(outer.x+inner.x*outer.width/inner.w,outer.y+inner.y*outer.width/inner.w);await panel.mouse.wheel(0,400);await panel.waitForTimeout(600);await source.waitForFunction(()=>document.querySelector('#box').scrollTop>300);
// Both directions pause, including routes from the source.
await panel.locator('#sync').uncheck();await frames[0].locator('#field').fill('Только телефон');await panel.waitForTimeout(250);assert.equal(await source.locator('#field').inputValue(),'Из планшета');
await source.locator('#field').fill('Только основная');await panel.waitForTimeout(250);assert.equal(await frames[0].locator('#field').inputValue(),'Только телефон');
await source.evaluate(()=>history.pushState(null,'','/paused'));await panel.waitForTimeout(600);assert(frames.every(f=>f.url()===site+'/'));
await source.evaluate(()=>history.replaceState(null,'','/'));await panel.waitForTimeout(400);await panel.locator('#sync').check();
// Return control to a phone, then to desktop, without rebroadcast loops.
await panel.bringToFront();await frames[0].locator('#field').fill('Снова вместе');await source.waitForFunction(()=>document.querySelector('#field').value==='Снова вместе');
await frames[0].locator('#next').evaluate(e=>e.scrollIntoView({block:'center'}));await panel.waitForTimeout(500);const navOuter=await (await frames[0].frameElement()).boundingBox();const navInner=await frames[0].locator('#next').evaluate(e=>{const r=e.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2,w:innerWidth};});await panel.mouse.click(navOuter.x+navInner.x*navOuter.width/navInner.w,navOuter.y+navInner.y*navOuter.width/navInner.w);await source.waitForURL('**/next');await panel.waitForFunction(()=>[...document.querySelectorAll('.pageurl')].every(e=>e.textContent.endsWith('/next')));await panel.waitForFunction(()=>[...document.querySelectorAll('.device-status')].every(x=>x.textContent==='Подключён'));
await source.bringToFront();await source.locator('#field').fill('Основная снова');await panel.waitForFunction(()=>document.querySelector('#status').textContent.length>0);frames=panel.frames().filter(f=>f.url().startsWith(site));await Promise.all(frames.map(f=>f.waitForFunction(()=>document.querySelector('#field').value==='Основная снова')));
console.log('PASS reverse phone/tablet input, nested scroll, password exclusion, bidirectional pause including route, mobile navigation and desktop takeover');
await source.locator('#next').click();await panel.waitForFunction(()=>[...document.querySelectorAll('.pageurl')].every(e=>e.textContent.endsWith('/next')));await panel.waitForFunction(()=>[...document.querySelectorAll('.device-status')].every(x=>x.textContent==='Подключён'));
await source.reload();await source.locator('#menu').click();await panel.waitForTimeout(300);frames=panel.frames().filter(f=>f.url().startsWith(site));assert((await Promise.all(frames.map(f=>f.locator('#result').textContent()))).every(x=>x==='Открыто'));
const opened=context.waitForEvent('page');await source.locator('#blank').click();const other=await opened;await other.waitForLoadState();assert.equal(source.url(),site+'/next');assert((await source.locator('#blank').getAttribute('target'))==='_blank');await other.close();assert(panel.frames().filter(f=>f.url().startsWith(site)).every(f=>f.url().endsWith('/next')));await source.bringToFront();
await source.locator('#submit').click();await source.waitForURL('**/post');await panel.waitForFunction(()=>[...document.querySelectorAll('.pageurl')].every(e=>e.textContent.endsWith('/post')));assert.equal(posts,1);
await panel.bringToFront();await panel.locator('#stop').click();await source.locator('#menu').click();assert.equal(await panel.locator('.device-status').first().textContent(),'Остановлен');await panel.locator('#start').click();await panel.waitForFunction(()=>document.querySelectorAll('.device-status').length===4&&[...document.querySelectorAll('.device-status')].every(x=>x.textContent==='Подключён'));await source.close();await panel.waitForFunction(()=>document.querySelector('#status').textContent.includes('Основная вкладка закрыта'));
assert.deepEqual(errors,[]);console.log('PASS desktop preserved, clicks/input/proportional scroll/navigation/reload, native target_blank, one form POST, stop/reconnect, source closed');
}finally{await context?.close();server.close();fs.rmSync(root,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1});
