const {chromium}=require('playwright');
const http=require('http'),assert=require('assert'),fs=require('fs'),path=require('path'),os=require('os');
let posts=0,slowLoads=0;
const fixture=`<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box}body{margin:0;font:18px system-ui;background:#edf6f0;color:#142c21}header{padding:24px;background:#176649;color:white}main{padding:22px}h1{font-size:28px}input,button,a{display:block;margin:18px 0;padding:12px}article{margin:22px 0;padding:22px;background:white;border-radius:8px}.tail{height:1800px;background:linear-gradient(#edf6f0,#91c4a8)}#box{height:120px;overflow:auto}#box>div{height:500px}.result{padding:20px}</style><a href="#" id="decoy" onclick="document.querySelector('#result').textContent='НЕВЕРНЫЙ ЭЛЕМЕНТ'">Логотип</a><header>ТЕСТОВЫЙ САЙТ АГЕНТСТВА</header><main><h1>Проверка мобильной страницы</h1><p id="metrics"></p><form action="/post" method="POST"><input name="name" placeholder="Ваше имя"><button type="button" id="menu" onclick="document.querySelector('#result').textContent='Меню открыто'">Меню</button><p id="result">Меню закрыто</p><button id="submit" type="submit">Отправить заявку</button></form><a href="/next" target="_blank">Следующая страница</a><a href="#" class="photo-link"><img src="/photo.svg" width="80" height="80" alt="Фото"></a><div id="gallery" hidden>Фото открыто</div><script>document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelector('#gallery').hidden=true;});document.querySelector('.photo-link').addEventListener('click',e=>{e.preventDefault();document.querySelector('#gallery').hidden=false;});if(innerWidth<400){document.querySelector('#decoy').remove();}</script><article>Три живых страницы в одной вкладке. Без отладчика.</article><div id="box"><div>Вложенная прокрутка</div></div><div class="tail"></div></main><script>document.querySelector('#metrics').textContent=innerWidth+' × '+innerHeight;</script>`;
(async()=>{const server=http.createServer((req,res)=>{if(req.method==='POST')posts++;res.writeHead(200,{'Content-Type':'text/html; charset=utf-8',...(req.url==='/protected'||req.url==='/next'?{'X-Frame-Options':'DENY','Content-Security-Policy':"default-src 'self' 'unsafe-inline'; frame-ancestors 'none'"}:{})});if(req.url==="/slow"&&++slowLoads===2)setTimeout(()=>res.end(fixture),2200);else res.end(fixture);}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const port=server.address().port;
const root=fs.mkdtempSync(path.join(os.tmpdir(),'mobile-qa-v2-'));const ext=path.join(root,'extension');fs.cpSync(path.resolve(__dirname,'../extension'),ext,{recursive:true});const manifest=JSON.parse(fs.readFileSync(path.join(ext,'manifest.json')));manifest.host_permissions=['http://127.0.0.1/*'];fs.writeFileSync(path.join(ext,'manifest.json'),JSON.stringify(manifest));
let c;try{
 c=await chromium.launchPersistentContext(path.join(root,'profile'),{channel:'chromium',headless:true,viewport:{width:1500,height:1120},ignoreDefaultArgs:['--disable-extensions'],args:['--enable-unsafe-extension-debugging']});
 const cd=await c.browser().newBrowserCDPSession();const {id}=await cd.send('Extensions.loadUnpacked',{path:ext});const panel=await c.newPage();await panel.goto(`chrome-extension://${id}/panel.html`);await panel.evaluate(()=>chrome.storage.local.set({preferences:{count:'4',compatibility:true}}));const warnings=[];panel.on('console',msg=>{if(msg.text().includes('can escape its sandboxing'))warnings.push(msg.text());});const errors=[];panel.on('pageerror',e=>errors.push(e.message));await panel.goto(`chrome-extension://${id}/panel.html?url=${encodeURIComponent('http://127.0.0.1:'+port+'/')}`);
 await panel.waitForFunction(()=>document.querySelectorAll('.device-status').length===4&&[...document.querySelectorAll('.device-status')].every(s=>s.textContent==='Подключён'),null,{timeout:15000});assert.equal(c.pages().length,2);assert.equal(panel.frames().length,5);async function realClick(frame,selector){await frame.locator(selector).evaluate(el=>el.scrollIntoView({block:'center'}));await panel.waitForTimeout(500);const outer=await (await frame.frameElement()).boundingBox();const info=await frame.locator(selector).evaluate(el=>{const r=el.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2,width:innerWidth};});await panel.mouse.click(outer.x+info.x*outer.width/info.width,outer.y+info.y*outer.width/info.width);}
 const frames=panel.frames().filter(f=>f.url().startsWith('http://127.0.0.1'));
 assert.deepEqual(await Promise.all(frames.map(f=>f.evaluate(()=>innerWidth))),[414,393,360,820]);assert(await panel.evaluate(()=>{const row=document.querySelector('#devices').getBoundingClientRect();const last=document.querySelector('.device:last-child').getBoundingClientRect();return Math.abs(row.right-last.right)<3;}));
 await frames[0].evaluate(()=>scrollTo(0,400));await panel.waitForTimeout(500);assert((await frames[1].evaluate(()=>scrollY))>300);assert((await frames[2].evaluate(()=>scrollY))>300);
 await frames[0].evaluate(()=>scrollTo(0,0));await panel.waitForTimeout(500);
 await realClick(frames[0],'#menu');await panel.waitForTimeout(700);console.log('MENU',await Promise.all(frames.map(f=>f.locator('#result').textContent())),await panel.locator('.device-status').allTextContents());assert(await frames[1].locator('#result').textContent()==='Меню открыто');assert(await frames[2].locator('#result').textContent()==='Меню открыто');
 await realClick(frames[0],'.photo-link img');await panel.waitForTimeout(400);assert(await frames[1].locator('#gallery').isVisible());assert(await frames[2].locator('#gallery').isVisible());assert(await frames[3].locator('#gallery').isVisible());assert.equal(await frames[1].locator('#result').textContent(),'Меню открыто');await panel.keyboard.press('Escape');await panel.waitForTimeout(300);assert((await Promise.all(frames.map(f=>f.locator('#gallery').isHidden()))).every(Boolean));
 await frames[0].locator('input').fill('Синхронный ввод');await panel.waitForTimeout(200);assert.equal(await frames[1].locator('input').inputValue(),'Синхронный ввод');assert.equal(await frames[2].locator('input').inputValue(),'Синхронный ввод');
 await frames[0].evaluate(()=>document.querySelector('#box').scrollTop=180);await panel.waitForTimeout(500);assert((await frames[1].evaluate(()=>document.querySelector('#box').scrollTop))>100);
 await panel.locator('#sync').uncheck();await frames[0].locator('input').fill('Только здесь');await panel.waitForTimeout(200);assert.equal(await frames[1].locator('input').inputValue(),'Синхронный ввод');await panel.locator('#sync').check();
 await realClick(frames[0],'a[target=_blank]');await panel.waitForTimeout(700);assert(frames.every(f=>f.url().endsWith('/next')));assert.equal(c.pages().length,2);
 assert(await panel.evaluate(()=>[...document.querySelectorAll('.screen')].every(e=>e.scrollLeft===0&&e.scrollTop===0)));await panel.screenshot({path:path.join(root,'preview.png'),fullPage:true});
 await realClick(frames[0],'#submit');await panel.waitForTimeout(700);assert.equal(posts,1);
 await panel.locator('#count').selectOption('5');await panel.waitForFunction(()=>document.querySelectorAll('.device-status').length===5&&[...document.querySelectorAll('.device-status')].every(s=>s.textContent==='Подключён'));assert.equal(c.pages().length,2);assert.equal(panel.frames().length,6);
 await panel.locator('#url').fill('http://127.0.0.1:'+port+'/protected');await panel.locator('#start').click();await panel.waitForTimeout(1000);console.log('START',await panel.evaluate(()=>({url:document.querySelector('#url').value,status:document.querySelector('#status').textContent,pages:[...document.querySelectorAll('.pageurl')].map(x=>x.textContent)})));await panel.waitForFunction(()=>[...document.querySelectorAll('.pageurl')].every(s=>s.textContent.endsWith('/protected')));await panel.waitForFunction(()=>[...document.querySelectorAll('.device-status')].every(s=>s.textContent==='Подключён'));assert.equal(panel.frames().length,6);
 await realClick(panel.frames().find(f=>f.url().includes('/protected')),'a[target=_blank]');await panel.waitForTimeout(1000);assert(panel.frames().filter(f=>f.url().startsWith('http:')).every(f=>f.url().endsWith('/next')));await panel.waitForFunction(()=>[...document.querySelectorAll('.device-status')].every(s=>s.textContent==='Подключён'));await panel.locator('.controls').first().locator('[data-action=back]').click();await panel.waitForFunction(()=>[...document.querySelectorAll('.pageurl')].every(s=>s.textContent.endsWith('/protected')));await panel.reload();await panel.waitForFunction(()=>document.querySelectorAll('.device-status').length===5&&[...document.querySelectorAll('.device-status')].every(s=>s.textContent==='Подключён'));assert(await panel.locator('#compatibility').isChecked());
 const worker=c.serviceWorkers()[0];const rules=await worker.evaluate(()=>chrome.declarativeNetRequest.getSessionRules());assert.equal(rules.length,1);assert(rules[0].condition.tabIds.length===1);assert.deepEqual(rules[0].condition.requestDomains,['127.0.0.1']);
 // A normal tab still receives the security headers, and cannot iframe this page.
 const ordinary=await c.newPage();const response=await ordinary.goto('http://127.0.0.1:'+port+'/protected');assert.equal(response.headers()['x-frame-options'],'DENY');await ordinary.close();
 await panel.locator('#count').selectOption('4');await panel.waitForFunction(()=>document.querySelectorAll('.device-status').length===4&&[...document.querySelectorAll('.device-status')].every(s=>s.textContent==='Подключён'));await panel.locator('#url').fill('http://127.0.0.1:'+port+'/slow');await panel.locator('#start').click();await panel.waitForFunction(()=>document.querySelector('.pageurl').textContent.endsWith('/slow')&&document.querySelector('.device-status').textContent==='Подключён');assert((await panel.locator('.device-status').allTextContents()).some(x=>x==='Загрузка'));await realClick(panel.frames().find(f=>f.url().endsWith('/slow')),'#menu');await panel.waitForFunction(()=>[...document.querySelectorAll('.device-status')].every(s=>s.textContent==='Подключён'));assert((await Promise.all(panel.frames().filter(f=>f.url().endsWith('/slow')).map(f=>f.locator('#result').textContent()))).every(x=>x==='Меню открыто'));console.log('PASS queued click while peer loads');
 const current=panel.frames().filter(f=>f.url().endsWith('/slow'));await current[1].goto('http://127.0.0.1:'+port+'/drift');await panel.waitForFunction(()=>[...document.querySelectorAll('.pageurl')].every(e=>e.textContent.endsWith('/slow')),null,{timeout:12000});console.log('PASS automatic recovery of divergent URL');
 await panel.locator('#url').fill('http://127.0.0.1:'+port+'/protected');await current[0].evaluate(()=>history.replaceState(null,'','#late'));await panel.waitForTimeout(200);assert((await panel.locator('#url').inputValue()).endsWith('/protected'));await panel.locator('#url').fill('http://127.0.0.1:'+port+'/slow');console.log('PASS late route cannot overwrite typed address');
 await panel.setViewportSize({width:1920,height:650});await panel.waitForTimeout(200);assert(await panel.evaluate(()=>{const row=document.querySelector('#devices').getBoundingClientRect();const last=document.querySelector('.device:last-child').getBoundingClientRect();return Math.abs(row.right-last.right)<3;}));
 await panel.locator('#stop').click();assert.equal((await worker.evaluate(()=>chrome.declarativeNetRequest.getSessionRules())).length,0);
 await panel.locator('#start').click();await panel.waitForFunction(()=>[...document.querySelectorAll('.device-status')].every(s=>s.textContent==='Подключён'));await panel.close();await new Promise(r=>setTimeout(r,300));assert.equal((await worker.evaluate(()=>chrome.declarativeNetRequest.getSessionRules())).length,0);
 assert.deepEqual(errors,[]);assert.deepEqual(warnings,[]);console.log('PASS v2.2: one panel/no extra tabs, 4→5 frames, scaled mouse clicks, protected link navigation, Back, preferences after reload, CSS widths, root+nested scroll sync, semantic click sync, input sync, sync off, same-tab navigation, one form POST, iframe compatibility scoped to panel, rules cleanup.');
}finally{await c?.close();server.close();fs.rmSync(root,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1});
